### ISSUE TITLE
node版本问题

### ISSUE THREAD

**Issue by shellGrace** [wakeadmin/bbt-tools#1]
目前项目是使用的node14, 在引入bbt之后发布构建有问题，bbt 目前使用的是16版本 这个有可能兼容嘛

**Comment by njikm2010** [comment]
虽然 `@wakeadmin/bbt` 要求 node 版本为16，但是这是针对于开发情况下，在使用时可以支持 node 14 （14.15.0）。
如果还有问题 麻烦提供下对应的错误日志

**Comment by shellGrace** [comment]
相关报错日志：
@wakeadmin/bbt@0.2.2: The engine "node" is incompatible with this module. Expected version ">=16.0.0". Got "14.20.0"
[17:48:16]warning @wakeadmin/bbt@0.2.2: The engine "pnpm" appears to be invalid.

我看bbt代码中指定了 engines，"node": ">=16.0.0", "pnpm": ">=8.0.0" 应该是这个引起的

**Comment by njikm2010** [comment]
由于 `pnpm 7` 版本与 `pnpm 8` 存在一些差异性，项目强制使用 `pnpm 8` 版本，因此没办法对其进行降级。
这里给出以下几种解决方法:
1. 在项目中使用 `--ignore-engines` 选项来绕过这个限制（不推荐）
2. 如果使用`pnpm`的话， 在`package.json`添加以下字段来强制绕开限制
```json
{
  "pnpm": {
    "overrides": {
      "@wakeadmin/bbt": {
        "engines": {
          "node": "*",
          "pnpm": "*"
        }
      }
    }
  }
}
```
3. 将 `@wakeadmin/bbt` 通过 `--ignore-engines` 安装到全局环境中

**Comment by njikm2010** [comment]
新版本移除了对 `nodejs` 的限制。
