### ISSUE TITLE
文本翻译失效

### ISSUE THREAD

**Issue by shellGrace** [wakeadmin/bbt-tools#2]
在bbt config 文件下配置了
```
translator: 'google',
  // other
  plugins: {
    translator: (textMap, target, sourceLanguage = 'zh') => {
      return Promise.resolve(
        Object.entries(textMap).map(([key, value]) => ({
          target,
          key,
          translatedText: `${target}`,
        })),
      );
    },
  },
```
执行 npx bbt translate -t google --force --api-key xxx
执行成功
但.csv 文件内容并未进行翻译，而是如下图所示, 写入了设置的默认语言 en 和 th 字符
<img width="1201" alt="image" src="https://github.com/wakeadmin/bbt-tools/assets/46156180/194d0221-45a2-4109-9261-39bee7e3bc30">

**Comment by njikm2010** [comment]
如果配置文件有 `plugins.translator` 字段，那么会直接使用其值作为翻译函数进行翻译。
在这里传入的依次为要翻译的原始文本，翻译的目标语言以及翻译的源语言
返回的对象里的 `translatedText` 为翻译之后的内容。
在这里，你直接返回了 `target`。 所以结果就如你得到的一样。

**Comment by shellGrace** [comment]
但是在没有写入plugins translator 的情况，直接执行 npx bbt translate -t google --force --api-key xxx 会翻译为空，文件没有任何变动

**Comment by njikm2010** [comment]
目录下是否有 `bbt-translate-error-xxxx-xx-xx.log` 文件，如果有的话代表 `API` 接口异常

**Comment by shellGrace** [comment]
我找到了报错文件，报错日志显示
```
target: en
key: test.list.796898-0 - text: 测试翻译
key: test.list.796898-1 - text: 翻译
Google Translation Error : Google Translation Error: 响应数据不正确 -> {
  "error": {
    "code": 400,
    "message": "API key not valid. Please pass a valid API key.",
    "errors": [
      {
        "message": "API key not valid. Please pass a valid API key.",
        "domain": "global",
        "reason": "badRequest"
      }
    ],
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "API_KEY_INVALID",
        "domain": "googleapis.com",
        "metadata": {
          "service": "translate.googleapis.com"
        }
      }
    ]
  }
}
```
查阅文档 INVALID_ARGUMENT 属于超出字符长度限制，但我从bbt.csv文件内，将79行的文本翻译缩减为两行的内容翻译 依然报错
文档来源 https://cloud.google.com/translate/quotas?hl=zh-cn#content-limit

**Comment by ivan-94** [comment]
检查一下是你这 API key 是否合法，从提示信息看是鉴权失败的了
