### ISSUE TITLE
这种情况该怎么借助bbt去维护语言包?

### ISSUE THREAD

**Issue by zhaowuyang** [wakeadmin/bbt-tools#3]
背景：3个uniapp项目中大多数词条都是相同的，怎么用同一个bbt插件去自动维护？而不是每个项目都下载一次bbt。

语言包位置有多处：
1. 根目录（应用词条）
2. locale目录（框架内置组件词条）
3. uni_modules目录（自定义组件词条）

需求：bbt通过src指定更新各个项目的语言包，或者作为独立桌面端软件程序，并非项目依赖导入的形式更佳。

期望：src支持项目外的文件夹路径
```
/** @type { import('@wakeadmin/bbt').IBBTProjectConfig } */
module.exports = {
    langs: ['zh-Hans', 'zh-Hant', 'en', 'id', 'jp', 'kr', 'my', 'th', 'vn', 'ger', 'es', 'pt', 'arab'],
    test: '.*\\.json$',
    exclude: ['node_modules'],
    src: 'C:\Users\Paneland-IT-005\Documents\HBuilderProjects\DataRolls\locale'
};
```

大佬，跪求最佳实践的建议，我会点star

**Comment by njikm2010** [comment]
目前`src`不支持多个目录，如果真的需要一个项目维护多个地方的语音包，只能将`src`设置成他们的最近父级目录然后在`exclude`里排除掉其他的目录，但是非常不推荐。

原则上还是建议根据项目来进行语言包的维护，如果有多个的项目的话，也可以考虑使用Monorepo的方式
